voting-app:
  build: ./voting-app/.
  ports:
    - "5000:80"

redis:
  image: dduportal/redis-arm
  ports: ["6379"]

worker:
  build: ./worker

db:
  image: zsoltm/postgresql-armhf
  volumes:
    - "myvolume:/var/lib/postgresql/data"

result-app:
  build: ./result-app/.
  ports:
    - "5001:80"
